#!/bin/bash

LDAPHOST=${LDAPHOST:-ldap-ci.docker.openmicroscopy.org}
LDAPPORT=${LDAPPORT:-10389}
LDAPPASS=${LDAPPASS:-secret}
LDAPDOMAIN=${LDAPDOMAIN:-dc=merge,dc=trout,dc=openmicroscopy,dc=org}

LDAPADD="ldapadd -v -h ${LDAPHOST} -p ${LDAPPORT} -x -D uid=admin,ou=system -w ${LDAPPASS}"

GROUP=$1
shift
USERDN="uid=test,ou=Users,$LDAPDOMAIN"

if [ $1 = "add" ]; then
    $LDAPADD << EOF
dn: cn=$GROUP,ou=Groups,$LDAPDOMAIN
objectClass: groupOfUniqueNames
objectClass: top
cn: $GROUP
uniqueMember: $USERDN
EOF

else
    echo "huh?"
    exit 2
fi
