#!/bin/bash

LDAPHOST=${LDAPHOST:-minke.openmicroscopy.org}
LDAPPORT=${LDAPPORT:-10389}
LDAPPASS=${LDAPPASS:-secret}
LDAPDOMAIN=${LDAPDOMAIN:-dc=openmicroscopy,dc=org}

ldapsearch -v -h $LDAPHOST -p $LDAPPORT -w $LDAPPASS -x -D uid=admin,ou=system -b $LDAPDOMAIN