#!/bin/bash

LDAPHOST=${LDAPHOST:-ldap-ci.docker.openmicroscopy.org}
LDAPPORT=${LDAPPORT:-10389}
LDAPPASS=${LDAPPASS:-secret}
GROUP=${GROUP:-ldap-private}

LDAPADD="ldapadd -v -h ${LDAPHOST} -p ${LDAPPORT} -x -D uid=admin,ou=system -w ${LDAPPASS}"
LDAPMODIFY="ldapmodify -v -h ${LDAPHOST} -p ${LDAPPORT} -x -D uid=admin,ou=system -w ${LDAPPASS}"
LDAPSEARCH="ldapmodify -v -h ${LDAPHOST} -p ${LDAPPORT} -x -D uid=admin,ou=system -w ${LDAPPASS}"

USER=$1
shift
DOMAIN="dc=merge,dc=trout,dc=openmicroscopy,dc=org"
USERDN="uid=$USER,ou=Users,$DOMAIN"

if  [ $1 = "add" ]; then
    $LDAPADD << EOF
version: 1

dn: $USERDN
objectClass: organizationalPerson
objectClass: person
objectClass: extensibleObject
objectClass: uidObject
objectClass: inetOrgPerson
objectClass: top
cn: $USER
givenName: $USER
sn: $USER
uid: $USER
mail: $USER@openmicroscopy.org
ou: Users
userpassword: ome
EOF
elif [ $1 = "in" ]; then
    shift
    GROUP=$1
    GROUPDN="cn=$GROUP,ou=Groups,$DOMAIN"

    $LDAPMODIFY << EOF
dn: $GROUPDN
changetype: modify
add: uniqueMember
uniqueMember: $USERDN
EOF
elif [ $1 = "out" ]; then
    shift
    GROUP=$1
    GROUPDN="cn=$GROUP,ou=Groups,$DOMAIN"

    $LDAPMODIFY << EOF
dn: $GROUPDN
changetype: modify
delete: uniqueMember
uniqueMember: $USERDN
EOF
elif [ $1 = "owner" ]; then
    shift
    GROUP=$1
    GROUPDN="cn=$GROUP,ou=Groups,$DOMAIN"

$LDAPMODIFY << EOF
dn: $GROUPDN
changetype: modify
add: owner
owner: $USERDN
EOF
elif [ $1 = "member" ]; then
    shift
    GROUP=$1
    GROUPDN="cn=$GROUP,ou=Groups,$DOMAIN"

    $LDAPMODIFY << EOF
dn: $GROUPDN
changetype: modify
delete: owner
owner: $USERDN
EOF
else
    echo "huh?"
    exit 2
fi
